cache:
  yarn: true
  directories:
    - node_modules
language: node_js
node_js:
  - "14"
branches:
  only:
    - main
before_install:
  - npm install -g npm@latest yarn
install:
  - yarn install
script:
  - yarn test
after_success:
  - yarn prepare
